name: Belding Productions
favicon: null
layout_spectrum: 0.307439778232947
typography_spectrum: 0.9697916228324175
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.014486830914393067
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
